apiVersion : v1
kind : Service
metadata:
  name : service-project
  namespace: aws-worker-uat
  labels:
    app : demo-voting-app

spec:
    type: LoadBalancer
    selector:
      app: demo-voting-app #select the deploment you are targetting
    ports:
      - port: 80
        name: tcp
#      - port: 80
#        name: http
